{{- if or .Values.redirectApi.username .Values.redirectApi.existingSecret }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redirect-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
{{- end }}
