{{- if .Values.build.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.build.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.build.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.build.roleArn | quote }}
  {{- end }}
{{- end }}
